pipeline {

    agent any

    stages {

        stage('Build') {
            steps {
                build job: 'Build_AMI'
            }
        }

        stage('Prepare') {
            steps {
                sh '''
                cd project/prod
                echo "variable "APP_INSTANCE_COUNT" {default = "0"}" >> var.tf
                aws s3 cp s3://${S3_BUCKET}/amivar.tf amivar.tf
                cat /var/jenkins_home/keys/remote-key > mykey
                cat /var/jenkins_home/keys/remote-key.pub > mykey.pub
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                cd project/prod
                terraform init
                terraform apply -auto-approve -var APP_INSTANCE_COUNT=1
                '''
            }
        }
    }
}
