pipeline {

    agent any

    stages {

        stage('Build') {
            steps {
                build job: 'Build_AMI'
            }
        }

        stage('Prepare') {
            steps {
                sh '''
                cd prod
                echo "variable "APP_INSTANCE_COUNT" {default = "0"}" >> var.tf
                aws s3 cp s3://${S3_BUCKET}/amivar amivar.tf
                touch mykey
                touch mykey.pub
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh 'terraform apply -auto-approve -var APP_INSTANCE_COUNT=1'
            }
        }

//         post {
//             always {
//                 build job:'/var/jenkins_home/workspace/DEPLOY_AMI', parameters: [string(name: 'S3_BUCKET', value: "${params.S3_BUCKET}")], propagate: false
//             }
//        }
    }
}
